### ISSUE TITLE
Issue with taking money

### ISSUE THREAD

**Issue by Unknownio** [LukeMccon/Airdrop#29]
The Issue that i have its with taking money from the player if they order a package it will not take any money for example one of my package is around 5k and i had my friend to test this (because i thought maybe that im op it will not take money) and he has 13k he order the package and still he had 13k after it got delivered

i have vault , luckperms , essentials , ...

**Comment by LukeMccon** [comment]
@Unknownio Thank you for reporting this, I was able to reproduce the issue
I will release a new version with the fix shortly

**Comment by LukeMccon** [comment]
@Unknownio Please update to Airdrop 3.0 , it should have a fix for this issue
