### ISSUE TITLE
taking money even when airdrop does not come...

### ISSUE THREAD

**Issue by homerek111** [LukeMccon/Airdrop#44]
plugin is taking player's money even when airdrop does not come (when player has some blocks above his head)
i think taking money should be cancelled in that situation

**Comment by homerek111** [comment]
@LukeMccon hello, is there any chance of fixing some bugs that i reported here on github?? :)

**Comment by LukeMccon** [comment]
@homerek111 Hi - yes. I just now saw these so Ill take a look

**Comment by homerek111** [comment]
> @homerek111 Hi - yes. I just now saw these so Ill take a look

Cool :) if you manage to fix this issue: https://github.com/LukeMccon/Airdrop/issues/45 I would love to have that plugin on my server - sadly with that bug I had to disable it for now :/

**Comment by LukeMccon** [comment]
@homerek111 Could you kindly share the version of airdrop and your server version?
I am unable to re-produce your issue
Players should in theory get a error saying the package cannot be dropped if there are blocks above their head

`/airdrop version` should give you this info - thanks!

**Comment by homerek111** [comment]
> @homerek111 Could you kindly share the version of airdrop and your server version? I am unable to re-produce your issue Players should in theory get a error saying the package cannot be dropped if there are blocks above their head
> 
> `/airdrop version` should give you this info - thanks!

@LukeMccon I used Aircraft-3.0.1-SNAPSHOT downloaded from here https://github.com/LukeMccon/Airdrop/releases/tag/v3.0.1

My server’s version: Paper version got-Paper-496 (MC: 1.20.4)

**Comment by LukeMccon** [comment]
@homerek111 Sorry for the late response! Just fixed this in 3.1.0
Thanks again for reporting these issues! very helpful
