### ISSUE TITLE
airdrop plugin breaks LumberJack plugin...

### ISSUE THREAD

**Issue by homerek111** [LukeMccon/Airdrop#45]
using Airdrop plugin makes falling logs from lumberjack plugin dissapear at the moment they hit the ground...
https://www.spigotmc.org/resources/lumberjack-tree-gravity-leaf-decay-custom-tree-drops.60306/

**Comment by LukeMccon** [comment]
Should be fixed in 3.1. Please open another issue if it is not working. Thanks!
